# Spring properties
spring:
  application:
    name: product-service

# Mongo properties
  data:
    mongodb:
      host: @mongo.host@
      port: @mongo.port@
      database: @mongo.database@


# HTTP Server
server:
  port: @http.port@
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: quebic_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh

